### ISSUE TITLE
Performance. Always think about performance.

### ISSUE THREAD

**Issue by danielf** [zejin/ORIE6125#1]
In the following piece of code:

```
X_bar = np.mean(X, axis=1)
sigma_hat = np.dot((X.T - X_bar).T, X.T - X_bar) / float(n)
tr_sigma_hat = sum(np.diag(sigma_hat))
```

Since you are only interested in the trace of sigma, you don't need to compute all the entries of it, only the diagonal entries. The way you are doing it it takes O(N^2), but this sounds silly once you are only interested in O(N) of these values.

Try to make comments on the asymptotic behavior of all your pieces of code. The code above was just an example.

**Comment by zejin** [comment]
Actually the return value is related to sigma_hat to some extent.
I was wondering if I could replace it with something else? Thanks.

```
X_bar = np.mean(X, axis=1)
sigma_hat = np.dot((X.T - X_bar).T, X.T - X_bar) / float(n)
tr_sigma_hat = sum(np.diag(sigma_hat))

return float(n) ** 2 / (n + 2) / (n - 1) * (np.linalg.norm(sigma_hat, 'fro') ** 2 \
- 1. / n * (tr_sigma_hat ** 2))
```
