### ISSUE TITLE
assertAlmostEquals vs assertEquals

### ISSUE THREAD

**Issue by skyler120** [zejin/ORIE6125#2]
When using assertAlmostEquals I get all tests passed.  When using assertEquals, I get two failed tests (particularly the middle tests).  Should I always use assertAlmostEquals for float numbers, or is there a potential precision accuracy issue?

**Comment by zejin** [comment]
I think using assertAlmostEquals is fine.

**Comment by danielf** [comment]
It is fine. Equality of floats is a myth, it simply doesn't happen. Never.
